package model.dao.daos;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import model.dao.DAO;
import model.dao.DAOInterface;

import java.util.LinkedList;

/**
 * ScholarYear generated by hbm2java
 */
public class ScholarYearDAO extends DAO implements DAOInterface {


	@Override
	public Object getById(int id) {
		return null;
	}

	@Override
	public boolean deleteById(int id, String employees) {
		return false;
	}

	@Override
	public boolean update(Object object) {
		return false;
	}

	@Override
	public boolean add(Object object) {
		return false;
	}



	@Override
	public LinkedList getAll() {
		return null;
	}

	@Override
	public int countAll() {
		return 0;
	}
}
