package model.dao.daos;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import model.beans.ScholarYear;
import model.dao.DAO;
import model.dao.DAOInterface;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;

/**
 * ScholarYear generated by hbm2java
 */
public class ScholarYearDAO extends DAO implements DAOInterface {

	public ScholarYear GetLastScholarYear(){
		try {
			ResultSet result = statement.executeQuery("SELECT * FROM scholar_year ORDER BY id DESC LIMIT 1;");;
			if (result.next()) {
				ScholarYear sy = new ScholarYear();
				sy.setId(result.getInt("id"));
				sy.setComments(result.getString("comments"));
				sy.setStartDate(result.getDate("start_date"));
				sy.setEndDate(result.getDate("end_date"));
				return sy;
			}


		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}

	@Override
	public Object getById(int id) {
		return null;
	}

	@Override
	public boolean deleteById(int id) {
		return false;
	}

	@Override
	public boolean update(Object object) {
		return false;
	}

	@Override
	public boolean add(Object object) {
		return false;
	}



	@Override
	public LinkedList getAll() {
		return null;
	}

	@Override
	public int countAll() {
		return 0;
	}
}
