package model.beans;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * StudentsBiblioInscId generated by hbm2java
 */
public class StudentsBiblioInsc implements java.io.Serializable {

	private Students student;
	private ScholarYear scholarYear;
	private Date dateInsc;

	public StudentsBiblioInsc() {
	}

	public Students getStudent() {
		return student;
	}

	public void setStudent(Students student) {
		this.student = student;
	}

	public ScholarYear getScholarYear() {
		return scholarYear;
	}

	public void setScholarYear(ScholarYear scholarYear) {
		this.scholarYear = scholarYear;
	}

	public Date getDateInsc() {
		return dateInsc;
	}

	public void setDateInsc(Date dateInsc) {
		this.dateInsc = dateInsc;
	}
}
