package model.beans;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String prenom;
	private Date dateNaiss;
	private String sexe;
	private String numBac;
	private Date dateInsc;
	private Set studentsBiblioInscs = new HashSet(0);
	private Set studentInscriptions = new HashSet(0);

	public Students() {
	}

	public Students(String nom, String prenom, Date dateNaiss, String sexe, String numBac, Date dateInsc) {
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaiss = dateNaiss;
		this.sexe = sexe;
		this.numBac = numBac;
		this.dateInsc = dateInsc;
	}

	public Students(String nom, String prenom, Date dateNaiss, String sexe, String numBac, Date dateInsc,
			Set studentsBiblioInscs, Set studentInscriptions) {
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaiss = dateNaiss;
		this.sexe = sexe;
		this.numBac = numBac;
		this.dateInsc = dateInsc;
		this.studentsBiblioInscs = studentsBiblioInscs;
		this.studentInscriptions = studentInscriptions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDateNaiss() {
		return this.dateNaiss;
	}

	public void setDateNaiss(Date dateNaiss) {
		this.dateNaiss = dateNaiss;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public String getNumBac() {
		return this.numBac;
	}

	public void setNumBac(String numBac) {
		this.numBac = numBac;
	}

	public Date getDateInsc() {
		return this.dateInsc;
	}

	public void setDateInsc(Date dateInsc) {
		this.dateInsc = dateInsc;
	}

	public Set getStudentsBiblioInscs() {
		return this.studentsBiblioInscs;
	}

	public void setStudentsBiblioInscs(Set studentsBiblioInscs) {
		this.studentsBiblioInscs = studentsBiblioInscs;
	}

	public Set getStudentInscriptions() {
		return this.studentInscriptions;
	}

	public void setStudentInscriptions(Set studentInscriptions) {
		this.studentInscriptions = studentInscriptions;
	}

}
