package model.beans;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * StudentInscription generated by hbm2java
 */
public class StudentInscription implements java.io.Serializable {

    private Students student;
    private Date dateInsc;
    private InscriptionPeriod inscriptionPeriod;
    private String level;

    public StudentInscription() {
    }

    public Students getStudent() {
        return student;
    }

    public void setStudent(Students student) {
        this.student = student;
    }

    public Date getDateInsc() {
        return dateInsc;
    }

    public void setDateInsc(Date dateInsc) {
        this.dateInsc = dateInsc;
    }

    public InscriptionPeriod getInscPeriod() {
        return this.inscriptionPeriod;
    }

	public InscriptionPeriod getInscriptionPeriod() {
		return inscriptionPeriod;
	}

	public void setInscriptionPeriod(InscriptionPeriod inscriptionPerion) {
		this.inscriptionPeriod = inscriptionPerion;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getLevel() {
        return this.level;
    }
}
